version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 860061945305.dkr.ecr.ap-south-1.amazonaws.com
    - REPOSITORY_URI=860061945305.dkr.ecr.ap-south-1.amazonaws.com/authenticationservice
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_URI
    - mvn clean package -Ddockerfile.skip
    - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
    - printenv
    - echo Build completed on `date`
    - echo $(docker images)
    - echo Pushing docker image
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' authenticationservice $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json